// <auto-generated />
using System;
using Hellion.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hellion.Core.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Hellion.Core.Database.DbCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    b.Property<int>("BankCode")
                        .HasColumnType("int")
                        .HasColumnName("bankCode");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("classId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int")
                        .HasColumnName("dexterity");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint")
                        .HasColumnName("exp");

                    b.Property<int>("FaceId")
                        .HasColumnType("int")
                        .HasColumnName("faceId");

                    b.Property<int>("Fp")
                        .HasColumnType("int")
                        .HasColumnName("fp");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("gender");

                    b.Property<int>("Gold")
                        .HasColumnType("int")
                        .HasColumnName("gold");

                    b.Property<uint>("HairColor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("hairColor");

                    b.Property<int>("HairId")
                        .HasColumnType("int")
                        .HasColumnName("hairId");

                    b.Property<int>("Hp")
                        .HasColumnType("int")
                        .HasColumnName("hp");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int")
                        .HasColumnName("intelligence");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("MapId")
                        .HasColumnType("int")
                        .HasColumnName("mapId");

                    b.Property<int>("Mp")
                        .HasColumnType("int")
                        .HasColumnName("mp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<float>("PosX")
                        .HasColumnType("float")
                        .HasColumnName("posX");

                    b.Property<float>("PosY")
                        .HasColumnType("float")
                        .HasColumnName("posY");

                    b.Property<float>("PosZ")
                        .HasColumnType("float")
                        .HasColumnName("posZ");

                    b.Property<int>("SkinSetId")
                        .HasColumnType("int")
                        .HasColumnName("skinSetId");

                    b.Property<int>("Slot")
                        .HasColumnType("int")
                        .HasColumnName("slot");

                    b.Property<int>("Stamina")
                        .HasColumnType("int")
                        .HasColumnName("stamina");

                    b.Property<int>("Strength")
                        .HasColumnType("int")
                        .HasColumnName("strength");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("IX_characters_accountId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_characters_name");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("Hellion.Core.Database.DbItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("characterId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int")
                        .HasColumnName("itemCount");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("itemId");

                    b.Property<int>("ItemSlot")
                        .HasColumnType("int")
                        .HasColumnName("itemSlot");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("IX_items_characterId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("Hellion.Core.Database.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Authority")
                        .HasColumnType("int")
                        .HasColumnName("authority");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("username");

                    b.Property<bool>("Verification")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("verification");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Hellion.Core.Database.DbItem", b =>
                {
                    b.HasOne("Hellion.Core.Database.DbCharacter", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Hellion.Core.Database.DbCharacter", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
